### ISSUE TITLE
Create eventmaster-datasource plugin for Grafana

### ISSUE THREAD

**Issue by bretep** [ContextLogic/eventmaster#4]
The grafana elasticsearch datasource doesn't work well for the way we've architected eventmaster. We should create a datasource plugin for grafana. The documentation to do so looks simple enough follow and implement.

https://github.com/grafana/simple-json-datasource
https://github.com/bergquist/fake-simple-json-datasource

**Comment by smcquay** [comment]
Fixed by #22
